name: Fear Releasing Method
favicon: null
layout_spectrum: 0.5139925
typography_spectrum: 0.4608209
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Fear Releasing Method
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DFEAF4'
    - '#383830'
    - '#91999B'
    - '#9BB4CE'
    - '#CED0B4'
  brandStrength: 0
  lightness: 0.08820321
  saturation: 0.5720665
  rhythmicContrast: 0.8108062
purpose: []
