layout_spectrum: 0.5139925
typography_spectrum: 0.4608209
color:
  saturation: 0.5720665
  lightness: 0.08820321
  brandStrength: 0
  brandColors:
    - '#DFEAF4'
    - '#383830'
    - '#91999B'
    - '#9BB4CE'
    - '#CED0B4'
  rhythmicContrast: 0.8108062
name: Fear Releasing Method
